[project]
name = "krp-working-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "acdh-tei-pyutils>=1.6",
]

[dependency-groups]
dev = [
    "ruff>=0.15.1",
]
